site_name: Dev
site_url: https://dev.tightbytes.com
edit_uri: "http://127.0.0.1:8000/docs/"
use_directory_urls: true
theme:
  name: material
  icon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - stylesheets/extras.css

nav:
  - Home: index.md

  - Work:
      - work/index.md
      - De-Cluttered Home: work/DClutter.md
      - Debugging a Site: work/debugsite.md
      - Website in Docker: work/websiteD.md

not_in_nav: |
  emily/2023/**
  emily/2024/**
  emily/2512/**
  emily/2601/**
  emily/2602/**
  archive/CG/**

plugins:
  - search
  - tags

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
